### ISSUE TITLE
[traderepublik] Depotübertrag

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#312] opened 2020-11-30 14:43 UTC
## Description
> Es wurden mehrere Positionen von Trade Republic übertragen

## Documents
<details><summary>UEBERTRAG_EINGANG_898762464_ord27485614_wkn903276_dat20200811_id900400513.pdf</summary><p>

```json
[
  [
    "Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).",
    "Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929",
    "Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de",
    "Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449",
    "Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé",
    "Consorsbank",
    "• 90318 Nürnberg",
    "Gdbamfwzkx Qgznc",
    "Jnqbyvxesm 0",
    "00478 Cümlqdqu",
    "Depotnummer",
    "4955835278",
    "9479346542",
    "/93",
    "Vermerk der Bank",
    "2000",
    "02",
    "Hinweis für Orderabrechnungen und Depotbuchungsanzeigen:",
    "Einwendungen wegen Unrichtigkeit oder Unvollständigkeit dieser Mitteilung müssen unverzüglich erhoben werden, vgl. Nummer B. Ziffer I. 11 (4) und (5) der",
    "Allgemeinen Geschäftsbedingungen (AGB Banken).",
    "Machen Sie Ihre Einwendungen in Textform",
    "geltend, genügt die Absendung innerhalb der Sechs-Wochen-Frist an die Consorsbank oder per Fax oder Mail an die",
    "unten angegebenen Adressen. Das Unterlassen rechtzeitiger Einwendungen gilt als Genehmigung.",
    "UEBERTRAG EINGANG",
    "11.08.2020",
    "Belegnummer:",
    "27485614",
    "Folg. Positionen haben wir per o.g.Datum Ihrem Bestand gutgeschrieben.",
    "Bezeichnung",
    "WKN",
    "Gazprom PJSC",
    "Nam.Akt.(Sp.ADRs)/2 RL 5",
    "903276",
    "Einheit",
    "Nennwert",
    "Verwahrart",
    "ST",
    "10,00000",
    "Girosammelverwahrung",
    "CBF 2126",
    "Komplette Stücke",
    "DIE O.G. WERTPAPIERE EMPFINGEN WIR VON:",
    "4043 HSBC TRINKAUS + BURKH.   9276036                       9943079",
    "Hinweis:",
    "Bitte",
    "beachten",
    "Sie,",
    "dass",
    "die",
    "Einstandsdaten",
    "des",
    "obigen",
    "Depoteingangs",
    "unabhängig",
    "von",
    "den",
    "Wertpapieren",
    "übertragen",
    "werden und deshalb zeitlich verzögert eingepflegt werden können.",
    "Die Verantwortung für die korrekte Durchführung des Übertrags und die Richtigkeit der übermittelten Daten liegt",
    "ausschließlich bei der abgebenden Bank. Bitte wenden Sie sich daher bei Reklamationen an das abgebende Kreditinstitut.",
    "Eine gesetzliche Verpflichtung zur Übermittlung der Daten besteht grundsätzlich nur für Banken mit Sitz in Deutschland.",
    "Zur",
    "Prüfung",
    "können",
    "Sie",
    "auf",
    "www.consorsbank.de",
    "in",
    "der",
    "Detailansicht",
    "der",
    "jeweiligen",
    "Wertpapierposition",
    "unter",
    "dem",
    "Reiter",
    "„Historie“ alle hinterlegten Einstandsdaten einsehen."
  ]
]

```

</p></details>

<details><summary>UEBERTRAG_EINGANG_898762464_ord27485630_wknA0D94M_dat20200811_id900400514.pdf</summary><p>

```json
[
  [
    "Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).",
    "Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929",
    "Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de",
    "Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449",
    "Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé",
    "Consorsbank",
    "• 90318 Nürnberg",
    "Drniojmbhw Qcvgi",
    "Bcjxyfhbph 1",
    "75553 Nüeuxxse",
    "Depotnummer",
    "6026399082",
    "1001716309",
    "/08",
    "Vermerk der Bank",
    "2000",
    "02",
    "Hinweis für Orderabrechnungen und Depotbuchungsanzeigen:",
    "Einwendungen wegen Unrichtigkeit oder Unvollständigkeit dieser Mitteilung müssen unverzüglich erhoben werden, vgl. Nummer B. Ziffer I. 11 (4) und (5) der",
    "Allgemeinen Geschäftsbedingungen (AGB Banken).",
    "Machen Sie Ihre Einwendungen in Textform",
    "geltend, genügt die Absendung innerhalb der Sechs-Wochen-Frist an die Consorsbank oder per Fax oder Mail an die",
    "unten angegebenen Adressen. Das Unterlassen rechtzeitiger Einwendungen gilt als Genehmigung.",
    "UEBERTRAG EINGANG",
    "11.08.2020",
    "Belegnummer:",
    "27485630",
    "Folg. Positionen haben wir per o.g.Datum Ihrem Bestand gutgeschrieben.",
    "Bezeichnung",
    "WKN",
    "ROYAL DUTCH SHELL",
    "REG. SHARES CLASS A EO -,07",
    "A0D94M",
    "Einheit",
    "Nennwert",
    "Verwahrart",
    "ST",
    "12,00000",
    "Girosammelverwahrung",
    "CBF 2126",
    "Komplette Stücke",
    "DIE O.G. WERTPAPIERE EMPFINGEN WIR VON:",
    "4043 HSBC TRINKAUS + BURKH.   9276031                       9943074",
    "Hinweis:",
    "Bitte",
    "beachten",
    "Sie,",
    "dass",
    "die",
    "Einstandsdaten",
    "des",
    "obigen",
    "Depoteingangs",
    "unabhängig",
    "von",
    "den",
    "Wertpapieren",
    "übertragen",
    "werden und deshalb zeitlich verzögert eingepflegt werden können.",
    "Die Verantwortung für die korrekte Durchführung des Übertrags und die Richtigkeit der übermittelten Daten liegt",
    "ausschließlich bei der abgebenden Bank. Bitte wenden Sie sich daher bei Reklamationen an das abgebende Kreditinstitut.",
    "Eine gesetzliche Verpflichtung zur Übermittlung der Daten besteht grundsätzlich nur für Banken mit Sitz in Deutschland.",
    "Zur",
    "Prüfung",
    "können",
    "Sie",
    "auf",
    "www.consorsbank.de",
    "in",
    "der",
    "Detailansicht",
    "der",
    "jeweiligen",
    "Wertpapierposition",
    "unter",
    "dem",
    "Reiter",
    "„Historie“ alle hinterlegten Einstandsdaten einsehen."
  ]
]

```

</p></details>

<details><summary>UEBERTRAG_EINGANG_898762464_ord27485637_wknA0HL9Z_dat20200811_id900400515.pdf</summary><p>

```json
[
  [
    "Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).",
    "Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929",
    "Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de",
    "Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449",
    "Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé",
    "Consorsbank",
    "• 90318 Nürnberg",
    "Rknypfztod Mcfwn",
    "Abvrsciusk 8",
    "92723 Aürilkak",
    "Depotnummer",
    "7065443613",
    "5453172763",
    "/09",
    "Vermerk der Bank",
    "2000",
    "02",
    "Hinweis für Orderabrechnungen und Depotbuchungsanzeigen:",
    "Einwendungen wegen Unrichtigkeit oder Unvollständigkeit dieser Mitteilung müssen unverzüglich erhoben werden, vgl. Nummer B. Ziffer I. 11 (4) und (5) der",
    "Allgemeinen Geschäftsbedingungen (AGB Banken).",
    "Machen Sie Ihre Einwendungen in Textform",
    "geltend, genügt die Absendung innerhalb der Sechs-Wochen-Frist an die Consorsbank oder per Fax oder Mail an die",
    "unten angegebenen Adressen. Das Unterlassen rechtzeitiger Einwendungen gilt als Genehmigung.",
    "UEBERTRAG EINGANG",
    "11.08.2020",
    "Belegnummer:",
    "27485637",
    "Folg. Positionen haben wir per o.g.Datum Ihrem Bestand gutgeschrieben.",
    "Bezeichnung",
    "WKN",
    "AT & T Inc.",
    "Registered Shares DL 1",
    "A0HL9Z",
    "Einheit",
    "Nennwert",
    "Verwahrart",
    "ST",
    "10,00000",
    "Girosammelverwahrung",
    "CBF 2126",
    "Komplette Stücke",
    "DIE O.G. WERTPAPIERE EMPFINGEN WIR VON:",
    "4043 HSBC TRINKAUS + BURKH.   9276034                       9943077",
    "Hinweis:",
    "Bitte",
    "beachten",
    "Sie,",
    "dass",
    "die",
    "Einstandsdaten",
    "des",
    "obigen",
    "Depoteingangs",
    "unabhängig",
    "von",
    "den",
    "Wertpapieren",
    "übertragen",
    "werden und deshalb zeitlich verzögert eingepflegt werden können.",
    "Die Verantwortung für die korrekte Durchführung des Übertrags und die Richtigkeit der übermittelten Daten liegt",
    "ausschließlich bei der abgebenden Bank. Bitte wenden Sie sich daher bei Reklamationen an das abgebende Kreditinstitut.",
    "Eine gesetzliche Verpflichtung zur Übermittlung der Daten besteht grundsätzlich nur für Banken mit Sitz in Deutschland.",
    "Zur",
    "Prüfung",
    "können",
    "Sie",
    "auf",
    "www.consorsbank.de",
    "in",
    "der",
    "Detailansicht",
    "der",
    "jeweiligen",
    "Wertpapierposition",
    "unter",
    "dem",
    "Reiter",
    "„Historie“ alle hinterlegten Einstandsdaten einsehen."
  ]
]

```

</p></details>

<details><summary>UEBERTRAG_EINGANG_898762464_ord27490812_wkn852684_dat20200811_id900569829.pdf</summary><p>

```json
[
  [
    "Consorsbank ist eine eingetragene Marke der BNP Paribas S.A. Niederlassung Deutschland (AG nach franz. Recht).",
    "Standort Nürnberg: Bahnhofstraße 55, 90402 Nürnberg, HRB Nürnberg 31129, USt-IdNr. DE191528929",
    "Fon +49 (0) 911 / 369-30 00, Fax +49 (0) 911 / 369-10 00, info@consorsbank.de, www.consorsbank.de",
    "Sitz der BNP Paribas S.A.: 16, boulevard des Italiens, 75009 Paris, Frankreich, Registergericht: R.C.S. Paris 662 042 449",
    "Président du Conseil d‘Administration (Präsident des Verwaltungsrates): Jean Lemierre, Directeur Général (Generaldirektor): Jean-Laurent Bonnafé",
    "Consorsbank",
    "• 90318 Nürnberg",
    "Ltylqxjurj Ftlhv",
    "Fikwnsuexr 7",
    "96367 Sütatttw",
    "Depotnummer",
    "3170719573",
    "2221757259",
    "/70",
    "Vermerk der Bank",
    "2000",
    "02",
    "Hinweis für Orderabrechnungen und Depotbuchungsanzeigen:",
    "Einwendungen wegen Unrichtigkeit oder Unvollständigkeit dieser Mitteilung müssen unverzüglich erhoben werden, vgl. Nummer B. Ziffer I. 11 (4) und (5) der",
    "Allgemeinen Geschäftsbedingungen (AGB Banken).",
    "Machen Sie Ihre Einwendungen in Textform",
    "geltend, genügt die Absendung innerhalb der Sechs-Wochen-Frist an die Consorsbank oder per Fax oder Mail an die",
    "unten angegebenen Adressen. Das Unterlassen rechtzeitiger Einwendungen gilt als Genehmigung.",
    "UEBERTRAG EINGANG",
    "11.08.2020",
    "Belegnummer:",
    "27490812",
    "Folg. Positionen haben wir per o.g.Datum Ihrem Bestand gutgeschrieben.",
    "Bezeichnung",
    "WKN",
    "TORONTO-DOMINION BANK, THE",
    "Registered Shares o.N.",
    "852684",
    "Einheit",
    "Nennwert",
    "Verwahrart",
    "ST",
    "3,00000",
    "Wertpapierrechnung in USA/Kanada",
    "CBL 62126",
    "Komplette Stücke",
    "DIE O.G. WERTPAPIERE EMPFINGEN WIR VON:",
    "0064                          6190423                       6190423",
    "Hinweis:",
    "Bitte",
    "beachten",
    "Sie,",
    "dass",
    "die",
    "Einstandsdaten",
    "des",
    "obigen",
    "Depoteingangs",
    "unabhängig",
    "von",
    "den",
    "Wertpapieren",
    "übertragen",
    "werden und deshalb zeitlich verzögert eingepflegt werden können.",
    "Die Verantwortung für die korrekte Durchführung des Übertrags und die Richtigkeit der übermittelten Daten liegt",
    "ausschließlich bei der abgebenden Bank. Bitte wenden Sie sich daher bei Reklamationen an das abgebende Kreditinstitut.",
    "Eine gesetzliche Verpflichtung zur Übermittlung der Daten besteht grundsätzlich nur für Banken mit Sitz in Deutschland.",
    "Zur",
    "Prüfung",
    "können",
    "Sie",
    "auf",
    "www.consorsbank.de",
    "in",
    "der",
    "Detailansicht",
    "der",
    "jeweiligen",
    "Wertpapierposition",
    "unter",
    "dem",
    "Reiter",
    "„Historie“ alle hinterlegten Einstandsdaten einsehen."
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by SirGibihm** [comment] 2020-12-02 21:43
Duplicate of #311 thus close

**Closed by SirGibihm** 2020-12-02 21:43 UTC
Labels: needs-triage, user-submitted
