### ISSUE TITLE
Trade Republik - Fusion

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#340] opened 2020-12-03 14:40 UTC
## Description
> Die Fusion der Unilever Aktien ( N.V. wird zu PLC )

## Document
<details><summary>pb16069526920927045330830512603(1).pdf</summary><p>

```json
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "Emdzckcps Idvkppcp",
    "Böcmzoovj. 39",
    "A 46104 Xgzlnw",
    "SEITE",
    "1",
    "von",
    "1",
    "DATUM",
    "02.12.2020",
    "DEPOT",
    "972875696",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "zwxwoqx@zexybsgaozdar.vxu",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DUAN",
    "/ d84b-9d66",
    "FUSION",
    "ÜBERSICHT",
    "NR.",
    "BUCHUNG",
    "WERTPAPIER",
    "ANZAHL",
    "1",
    "Ausbuchung",
    "Unilever N.V.",
    "Aandelen op naam EO -,16",
    "NL0000388619",
    "20 Stk.",
    "2",
    "Einbuchung",
    "Unilever PLC",
    "Registered Shares LS -,031111",
    "GB00B10RZP78",
    "20 Stk.",
    "Unilever PLC Registered Shares LS -,031111 in Girosammelverwahrung.",
    "Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.",
    "Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie",
    "Leistung."
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/da467f32

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment] 2020-12-03 15:30
Duplicate of #333

**Closed by dredav** 2020-12-03 15:30 UTC
Labels: needs-triage, user-submitted
