### ISSUE TITLE
[Trade Republic] - Aktien-Split

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#502] opened 2020-12-15 20:13 UTC
## Description
> Aktien-Split einarbeiten.

## Document
<details><summary>pb15986527625055220027670906082.pdf</summary><p>

```json
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "Zrxyqps Sztojezzfo",
    "Zdtozihcmuußg 2X",
    "F 69882 Wvkewkjiwkew",
    "SEITE",
    "1",
    "von",
    "1",
    "DATUM",
    "28.08.2020",
    "DEPOT",
    "101917665",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "fquwtmv@huecxbnyzrxyv.nio",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DUAN / 2020-08-14 / 78677563 / d76c-6d9c",
    "SPLIT",
    "ÜBERSICHT",
    "NR.",
    "BUCHUNG",
    "WERTPAPIER",
    "ANZAHL",
    "1",
    "Einbuchung",
    "Apple Inc.",
    "Registered Shares o.N.",
    "US0378331005",
    "6 Stk.",
    "Apple Inc. Registered Shares o.N. in Girosammelverwahrung.",
    "Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.",
    "Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie",
    "Leistung."
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment] 2020-12-16 18:40
Duplicate of #451

**Closed** 2020-12-16 18:40 UTC
Labels: user-submitted, wontfix
