### ISSUE TITLE
Unilever

### ISSUE THREAD

**Issue by codeofsumit** [codeofsumit/tresor-import#412] opened 2020-12-09 05:56 UTC
## Description
> Umtausch 

## Document
<details><summary>Ausführungsanzeige.pdf</summary><p>

```json
[
  [
    "TRADE REPUBLIC BANK GMBH",
    "KASTANIENALLEE 32",
    "10435 BERLIN",
    "Ynjxylnm Bmxjqe",
    "Rfvowwyn-Opblxhf-Ynaaßz 04",
    "N 57204 Cojmsctf Lkcnyzotcstypgm",
    "SEITE",
    "1",
    "von",
    "1",
    "DATUM",
    "02.12.2020",
    "DEPOT",
    "157693801",
    "Trade Republic Bank GmbH",
    "Kastanienallee 32",
    "10435 Berlin",
    "www.traderepublic.com",
    "vijckiz@okyddkchdrcsc.qzm",
    "Sitz der Gesellschaft: Düsseldorf",
    "AG Düsseldorf HRB 85864",
    "USt-ID DE307510626",
    "Geschäftsführer",
    "Andreas Willius",
    "Karsten Müller",
    "DUAN",
    "/ 96cf-1854",
    "FUSION",
    "ÜBERSICHT",
    "NR.",
    "BUCHUNG",
    "WERTPAPIER",
    "ANZAHL",
    "1",
    "Ausbuchung",
    "Unilever N.V.",
    "Aandelen op naam EO -,16",
    "NL0000388619",
    "14 Stk.",
    "2",
    "Einbuchung",
    "Unilever PLC",
    "Registered Shares LS -,031111",
    "GB00B10RZP78",
    "14 Stk.",
    "Unilever PLC Registered Shares LS -,031111 in Girosammelverwahrung.",
    "Diese Abrechnung wird maschinell erstellt und daher nicht unterschrieben.",
    "Sofern keine Umsatzsteuer ausgewiesen ist, handelt es sich gem. § 4 Nr. 8 UStG um eine umsatzsteuerfreie",
    "Leistung."
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment] 2020-12-10 20:51
Duplicate of #333.

**Closed by dredav** 2020-12-10 20:51 UTC
Labels: needs-triage, transfer-in-out, user-submitted
